%Files to include: Game_2048, removeSpllash, boardSlider, tileGenerator

function Game_2048()

% Create Figure
f = figure('Name','2048','Color','w', 'Position'...
    ,[710,315,560,550],'MenuBar','none');

% Title, score text, text box for actual score
title = uicontrol(f,'Style','text', 'String', '2048',...
    'BackgroundColor','w','FontSize', 30, ...
    'Position', [30 420, 100, 100], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'left','FontName', 'Comic Sans MS');

sccoretxt = uicontrol(f,'Style','text', 'String', 'Score:',...
    'BackgroundColor','w','FontSize', 30, ...
    'Position', [280 420, 150, 100], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'left','FontName', 'Comic Sans MS');

score = uicontrol(f,'Style','text', 'String', '0',...
    'BackgroundColor','w','FontSize', 30, ...
    'Position', [401 419, 100, 100], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'left','FontName', 'Comic Sans MS');

% % Key press controls
%keypress = uicontrol(f, 'KeyPressFcn', @myBoardSlider);

% Splash screen
splash = uicontrol(f,'Style','text', 'String', ...
    'Welcome to 2048!','FontName', 'Comic Sans MS',...
    'ForegroundColor','w','FontSize', 30,'Position',...
    [0, 0, 560, 550],'ForegroundColor','k', 'HorizontalAlignment', 'center');

start = uicontrol(f, 'Style','pushbutton','FontName', 'Comic Sans MS','String','Start!', ...
                     'FontSize',15, 'Position', [240 200 100 40]); 
start.Callback = @removeSplash;

% Array
arr = [0,0,0,0;0,0,0,0;0,0,0,0;0,0,0,0];




end