% Main function

function play2048
scorenum = 0;
play = false;

%Initialize an array to keep track of your values as the game is played
arr = [];
endd = false;
% Create Figure
f = figure('Name','2048','Color','[0.8 0.8 0.8]', 'Position'...
    ,[710,315,560,550],'MenuBar','none', 'NumberTitle', 'off',...
    'Resize', 'off', 'KeyReleaseFcn',{@myBoardSlider,arr, scorenum});

% Pause button & Command, Title, Score info
pausebtn = uicontrol(f, 'Style','pushbutton','FontName', ...
    'Comic Sans MS','String','Pause', ...
    'FontSize',15, 'Position', [440 20 100 40]);
pausebtn.Callback = @pauseGame;

title = uicontrol(f,'Style','text', 'String', '2048',...
    'BackgroundColor','[0.8 0.8 0.8]','FontSize', 30, ...
    'Position', [110 420, 100, 100], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'left','FontName', 'Comic Sans MS');

sccoretxt = uicontrol(f,'Style','text', 'String', 'Score:',...
    'BackgroundColor','[0.8 0.8 0.8]','FontSize', 30, ...
    'Position', [280 420, 150, 100], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'left','FontName', 'Comic Sans MS');

score = uicontrol(f,'Style','text', 'String', '0',...
    'BackgroundColor','[0.8 0.8 0.8]','FontSize', 30, ...
    'Position', [401 419, 100, 100], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'left','FontName', 'Comic Sans MS');

% Title, score text, text box for actual score
width = [110   210   310   410];
height = [92   189   286   383];

% Game Boxes
s16 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(4), height(1), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s15 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(4), height(2), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s14 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize',30, ...
    'Position', [width(4), height(3), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s13 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(4), height(4), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s12 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(3), height(1), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s11 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(3), height(2), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s10 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(3), height(3), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s9 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(3), height(4), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s8 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(2), height(1), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s7 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(2), height(2), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s6 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(2), height(3), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s5 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(2), height(4), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s4 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(1), height(1), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s3 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(1), height(2), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s2 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(1), height(3), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

s1 = uicontrol(f,'Style','text', 'String', '',...
    'BackgroundColor','y','FontSize', 30, ...
    'Position', [width(1), height(4), 55, 55], 'ForegroundColor',...
    'k', 'HorizontalAlignment', 'center','FontName', 'Comic Sans MS');

% Create a quit button (it can use the callback function quitGame provided
% below)
quitbtn = uicontrol(f, 'Style','pushbutton','FontName', ...
    'Comic Sans MS','String','Quit', ...
    'FontSize',15, 'Position', [20 20 100 40]);

%Update the display to show the beginning board with the new tiles
name = ['Welcome to 2048, ' getenv('username') '!'];

% Splash screen  & Commands
splash = uicontrol(f,'Style','text', 'String', ...
    name,'FontName', 'Comic Sans MS',...
    'ForegroundColor','w','FontSize', 30,'Position',...
    [0, 0, 561, 551],'ForegroundColor','k', 'HorizontalAlignment', 'center');

start = uicontrol(f, 'Style','pushbutton','FontName', 'Comic Sans MS','String','Start!', ...
    'FontSize',15, 'Position', [240 200 100 40]);

start.Callback = {@removeSplash, arr};
quitbtn.Callback = @quitGame;
end

function quitGame(f,event) % fill in the two inputs for a callback function

% does anything extra you would like to put in

f = gcf;
childs = allchild(f);

qtxt = uicontrol(f, 'Style','text','String','Quiting... :(', ...
    'FontSize',50, 'Position', [0 0 561 551], ...
    'BackgroundColor','k','ForegroundColor','w', ...
    'HorizontalAlignment','center');
pause(0.7);

% closes the figure
close(f);

end

function pauseGame(f,event) % fill in the two inputs for a callback function

% does anything extra you would like to put in

f = gcf;
childs = allchild(f);

ptxt = uicontrol(f, 'Style','text','String','Paused', ...
    'FontSize',50, 'Position', [0 0 561 551], ...
    'BackgroundColor','k','ForegroundColor','w', ...
    'HorizontalAlignment','center');

unpausebtn = uicontrol(f, 'Style','pushbutton','FontName', ...
    'Comic Sans MS','String','UnPause', ...
    'FontSize',15, 'Position', [230 225 100 40]);
unpausebtn.Callback = @removeSplash;

end


